### ISSUE TITLE
Local build doesn't work

### ISSUE THREAD

**Issue by rfink** [CircleCI-Public/circleci-demo-go#4]
Local build on this doesn't work - errors out:

go get github.com/jstemmer/go-junit-report
package github.com/jstemmer/go-junit-report: mkdir /go/src/github.com/jstemmer/: permission denied
Error: Exited with code 1
Step failed

**Comment by zzak** [comment]
Hello @rfink!

Could you try pulling the latest version and trying again?

Also make sure you `circleci update` locally to get the latest version of the CLI.

If you're still having troubles please feel free to re-open this ticket.
